// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
  show defaultTargetPlatform, kIsWeb, TargetPlatform;
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCX91l9TGauWeabhe99dQtIJSOuhkDO1R8',
    appId: '1:503078089220:web:b044fe4e0f58c7384dfb51',
    messagingSenderId: '503078089220',
    projectId: 'learning-english-7bc45',
    authDomain: 'learning-english-7bc45.firebaseapp.com',
    storageBucket: 'learning-english-7bc45.firebasestorage.app',
    measurementId: 'G-V5002LZLYB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeo7yyn8IIc-sWQUhW0CkhJYxlkv2zdR4',
    appId: '1:503078089220:android:34fc72eac13ee13a4dfb51',
    messagingSenderId: '503078089220',
    projectId: 'learning-english-7bc45',
    storageBucket: 'learning-english-7bc45.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFwex8l8M1lxIUactYsYL5-LQ8ow-0oZg',
    appId: '1:503078089220:ios:920018028bbb83f34dfb51',
    messagingSenderId: '503078089220',
    projectId: 'learning-english-7bc45',
    storageBucket: 'learning-english-7bc45.firebasestorage.app',
    iosBundleId: 'com.example.learnEnglish',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFwex8l8M1lxIUactYsYL5-LQ8ow-0oZg',
    appId: '1:503078089220:ios:920018028bbb83f34dfb51',
    messagingSenderId: '503078089220',
    projectId: 'learning-english-7bc45',
    storageBucket: 'learning-english-7bc45.firebasestorage.app',
    iosBundleId: 'com.example.learnEnglish',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCX91l9TGauWeabhe99dQtIJSOuhkDO1R8',
    appId: '1:503078089220:web:95311f6848cbfe054dfb51',
    messagingSenderId: '503078089220',
    projectId: 'learning-english-7bc45',
    authDomain: 'learning-english-7bc45.firebaseapp.com',
    storageBucket: 'learning-english-7bc45.firebasestorage.app',
    measurementId: 'G-77QPG777ZM',
  );

}