// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANNtqDI1B2Nznkz5JJWKxBIqmY8-LdV9E',
    appId: '1:742280195262:web:b329172879d77e53bc42ef',
    messagingSenderId: '742280195262',
    projectId: 'learning-english-moblie',
    authDomain: 'learning-english-moblie.firebaseapp.com',
    storageBucket: 'learning-english-moblie.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9_33K33BRfAuCWVr5SD3TmlU1P-7WThA',
    appId: '1:742280195262:android:62a2d018b60bbefcbc42ef',
    messagingSenderId: '742280195262',
    projectId: 'learning-english-moblie',
    storageBucket: 'learning-english-moblie.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnazEHmbo8Vurx-LmnU44RaCaDRKkX4LU',
    appId: '1:742280195262:ios:9b7ee183ac572579bc42ef',
    messagingSenderId: '742280195262',
    projectId: 'learning-english-moblie',
    storageBucket: 'learning-english-moblie.firebasestorage.app',
    iosBundleId: 'com.example.learnEnglish',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnazEHmbo8Vurx-LmnU44RaCaDRKkX4LU',
    appId: '1:742280195262:ios:9b7ee183ac572579bc42ef',
    messagingSenderId: '742280195262',
    projectId: 'learning-english-moblie',
    storageBucket: 'learning-english-moblie.firebasestorage.app',
    iosBundleId: 'com.example.learnEnglish',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyANNtqDI1B2Nznkz5JJWKxBIqmY8-LdV9E',
    appId: '1:742280195262:web:06c2eab6a96b3c1dbc42ef',
    messagingSenderId: '742280195262',
    projectId: 'learning-english-moblie',
    authDomain: 'learning-english-moblie.firebaseapp.com',
    storageBucket: 'learning-english-moblie.firebasestorage.app',
  );

}